project_id = "xfxqwlbqysiezqdpeqpv"

[auth]
enabled = true
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[functions.iasted-chat]
verify_jwt = true

[functions.iasted-stt]
verify_jwt = true

[functions.iasted-tts]
verify_jwt = true
